name: '[BACKEND] Java CI with Maven'

on:
  workflow_call:
    inputs:
      skip:
        required: false
        type: boolean
        default: false

jobs:
  check-skip:
    name: Verificar se deve pular CI
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.check.outputs.should_skip }}
    steps:
      - name: Verifica variÃ¡vel skip
        id: check
        run: |
          if [[ "${{ inputs.skip }}" == "true" ]]; then
            echo "âšª Nenhuma mudanÃ§a detectada, pulando build."
            echo "should_skip=true" >> $GITHUB_OUTPUT
          else
            echo "ðŸŸ¢ MudanÃ§as detectadas, executando build."
            echo "should_skip=false" >> $GITHUB_OUTPUT
          fi

  maven-build:
    needs: check-skip
    if: ${{ needs.check-skip.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 Corretto
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'

      - name: Build and package
        working-directory: ./backend
        run: mvn clean install -B -T 4C

      - name: Save .jar as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: backend/target/*.jar

  docker-build:
    needs:
      - check-skip
      - maven-build
    if: ${{ needs.check-skip.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download .jar artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: backend/target/

      - name: Build Docker image
        working-directory: ./backend
        run: docker build --no-cache -t aex-jar:test .
