name: '[BACKEND] Java CI with Maven'

on:
  workflow_call:
    inputs:
      run_ci:
        required: false
        type: boolean
        default: false

jobs:
  maven-build:
    if: ${{ inputs.run_ci }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 Corretto
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'

      - name: Build and package
        working-directory: ./backend
        run: mvn clean install -B -T 4C

      - name: Save .jar as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: backend/target/*.jar

  docker-build:
    needs:
      - check-skip
      - maven-build
    if: ${{ inputs.run_ci }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download .jar artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: backend/target/

      - name: Build Docker image
        working-directory: ./backend
        run: docker build --no-cache -t aex-jar:test .
