name: '[FRONTEND] CI'

on:
  workflow_call:
    inputs:
      run_ci:
        required: false
        type: boolean
        default: false
jobs:
  build:
    if: ${{ inputs.run_ci }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Rodando CI de frontend..."
